#pragma once
class Enums
{
public:
	enum rarity { NORMAL=0, MAGIC, RARE, UNIQUE };
	enum YNE { YES, NO, EITHER};

	enum ParserMode
	{
		NOTHING,
		IS_CORRUPTED,
		LINKED_SOCKETS,
		RARITY,
		CLASS,
		FONT_SIZE,
		TEXT_COLOR,
		BORDER_COLOR,
		BACKGROUND_COLOR,
		PLAY_ALERT_SOUND,
		ALERT_SOUND,
		RAY,
		MINIMAP_ICON,
		SHOW,
		HIDE,
		BASETYPE,
		IS_SHAPER_ITEM,
		ITEM_LEVEL,
		EXPLICIT_MOD,
		IDENTIFIED,
		IS_ELDER_ITEM,
		DROP_LEVEL,
		SOCKETS,
		IS_FRACTURED_ITEM,
		WIDTH,
		HEIGHT,
		IS_SYNTHESISED_ITEM,
		IS_ANY_ENCHANTMENT,
		QUALITY,
		SOCKET_GROUP,
		STACK_SIZE,
		GEM_LEVEL,
		IS_ELDER_MAP,
		IS_SHAPER_MAP,
		MAP_TIER,
		DISABLE_DROP_SOUND,
		PROPHECY
	};
	enum GameColors {RED, GREEN,BLUE, BROWN, WHITE, YELLOW};
	enum IconShape {CIRCLE, DIAMOND,HEXAGON, SQUARE, STAR, TRIANGLE};
	enum IconSize {LARGE, MEDIUM, SMALL};
	enum ConditionSymbols {LEQUAL, LESS, EQUAL, BIGGER, BEQUAL};

	enum PositionMaster {WINDOW, FILTER_BLOCK, SCREEN};
	enum PositionMode {LEFT, MID, RIGHT, UP, DOWN};
	enum ButtonType
	{
		BUTTON_NONE,
		BUTTON_CORRUPTION,
		BUTTON_CONDITION_LINKS, BUTTON_LINKS,
		BUTTON_CONDITION_RARITY, BUTTON_RARITY,
		BUTTON_FONT_SIZE, BUTTON_TEXT_COLOR, BUTTON_BORDER_COLOR, BUTTON_BG_COLOR,
		BUTTON_SHAPER_ITEM,
		BUTTON_ELDER_ITEM,
		BUTTON_IDENTIFIED,
		BUTTON_CONDITION_SOCKETS, BUTTON_SOCKETS,
		BUTTON_FRACTURED,
		BUTTON_SYNTHESISED,
		BUTTON_CONDITION_DROP_LEVEL, BUTTON_DROP_LEVEL,
		BUTTON_CONDITION_ITEM_LEVEL, BUTTON_ITEM_LEVEL,
		BUTTON_CONDITION_WIDTH, BUTTON_WIDTH,
		BUTTON_CONDITION_HEIGHT, BUTTON_HEIGHT,
		BUTTON_ANY_ENCHANTMENT,
		BUTTON_CONDITION_QUALITY, BUTTON_QUALITY,
		BUTTON_SOCKET_GROUP,
		BUTTON_CONDITION_STACK_SIZE, BUTTON_STACK_SIZE,
		BUTTON_CONDITION_GEM_LEVEL, BUTTON_GEM_LEVEL,
		BUTTON_ELDER_MAP,
		BUTTON_SHAPER_MAP,
		BUTTON_CONDITION_MAP_TIER, BUTTON_MAP_TIER
	};

};
